//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.24 at 11:20:52 PM CEST 
//


package basexdb.centralna;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="banke" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="naziv">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="swift">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[A-Z]{4}[A-Z]{2}[0-9A-Z]{2}([0-9A-Z]{3})?"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="stanje">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;totalDigits value="15"/>
 *                         &lt;fractionDigits value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="racun">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="18"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="brojacPoslednjePoslateNotifikacije" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="brojacPoslednjegPoslatogMTNaloga" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="brojacPoslednjegPrimljenogMTNaloga" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="banka">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="nazivBanke">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="255"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "banke",
    "brojacPoslednjePoslateNotifikacije",
    "brojacPoslednjegPoslatogMTNaloga",
    "brojacPoslednjegPrimljenogMTNaloga"
})
@XmlRootElement(name = "centralnaSema")
public class CentralnaSema {

    @XmlElement(required = true)
    protected List<CentralnaSema.Banke> banke;
    protected Integer brojacPoslednjePoslateNotifikacije;
    protected Integer brojacPoslednjegPoslatogMTNaloga;
    protected CentralnaSema.BrojacPoslednjegPrimljenogMTNaloga brojacPoslednjegPrimljenogMTNaloga;

    /**
     * Gets the value of the banke property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the banke property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBanke().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CentralnaSema.Banke }
     * 
     * 
     */
    public List<CentralnaSema.Banke> getBanke() {
        if (banke == null) {
            banke = new ArrayList<CentralnaSema.Banke>();
        }
        return this.banke;
    }

    /**
     * Gets the value of the brojacPoslednjePoslateNotifikacije property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBrojacPoslednjePoslateNotifikacije() {
        return brojacPoslednjePoslateNotifikacije;
    }

    /**
     * Sets the value of the brojacPoslednjePoslateNotifikacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBrojacPoslednjePoslateNotifikacije(Integer value) {
        this.brojacPoslednjePoslateNotifikacije = value;
    }

    /**
     * Gets the value of the brojacPoslednjegPoslatogMTNaloga property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBrojacPoslednjegPoslatogMTNaloga() {
        return brojacPoslednjegPoslatogMTNaloga;
    }

    /**
     * Sets the value of the brojacPoslednjegPoslatogMTNaloga property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBrojacPoslednjegPoslatogMTNaloga(Integer value) {
        this.brojacPoslednjegPoslatogMTNaloga = value;
    }

    /**
     * Gets the value of the brojacPoslednjegPrimljenogMTNaloga property.
     * 
     * @return
     *     possible object is
     *     {@link CentralnaSema.BrojacPoslednjegPrimljenogMTNaloga }
     *     
     */
    public CentralnaSema.BrojacPoslednjegPrimljenogMTNaloga getBrojacPoslednjegPrimljenogMTNaloga() {
        return brojacPoslednjegPrimljenogMTNaloga;
    }

    /**
     * Sets the value of the brojacPoslednjegPrimljenogMTNaloga property.
     * 
     * @param value
     *     allowed object is
     *     {@link CentralnaSema.BrojacPoslednjegPrimljenogMTNaloga }
     *     
     */
    public void setBrojacPoslednjegPrimljenogMTNaloga(CentralnaSema.BrojacPoslednjegPrimljenogMTNaloga value) {
        this.brojacPoslednjegPrimljenogMTNaloga = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="naziv">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="swift">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[A-Z]{4}[A-Z]{2}[0-9A-Z]{2}([0-9A-Z]{3})?"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="stanje">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;totalDigits value="15"/>
     *               &lt;fractionDigits value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="racun">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="18"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naziv",
        "swift",
        "stanje",
        "racun"
    })
    public static class Banke {

        @XmlElement(required = true)
        protected String naziv;
        @XmlElement(required = true)
        protected String swift;
        @XmlElement(required = true)
        protected BigDecimal stanje;
        @XmlElement(required = true)
        protected String racun;

        /**
         * Gets the value of the naziv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaziv() {
            return naziv;
        }

        /**
         * Sets the value of the naziv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaziv(String value) {
            this.naziv = value;
        }

        /**
         * Gets the value of the swift property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSwift() {
            return swift;
        }

        /**
         * Sets the value of the swift property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSwift(String value) {
            this.swift = value;
        }

        /**
         * Gets the value of the stanje property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getStanje() {
            return stanje;
        }

        /**
         * Sets the value of the stanje property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setStanje(BigDecimal value) {
            this.stanje = value;
        }

        /**
         * Gets the value of the racun property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRacun() {
            return racun;
        }

        /**
         * Sets the value of the racun property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRacun(String value) {
            this.racun = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="banka">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="nazivBanke">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="255"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "banka"
    })
    public static class BrojacPoslednjegPrimljenogMTNaloga {

        protected List<CentralnaSema.BrojacPoslednjegPrimljenogMTNaloga.Banka> banka;

        /**
         * Gets the value of the banka property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the banka property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBanka().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CentralnaSema.BrojacPoslednjegPrimljenogMTNaloga.Banka }
         * 
         * 
         */
        public List<CentralnaSema.BrojacPoslednjegPrimljenogMTNaloga.Banka> getBanka() {
            if (banka == null) {
                banka = new ArrayList<CentralnaSema.BrojacPoslednjegPrimljenogMTNaloga.Banka>();
            }
            return this.banka;
        }
        
        public CentralnaSema.BrojacPoslednjegPrimljenogMTNaloga.Banka getBankaByNaziv(String naziv) {
        	for(CentralnaSema.BrojacPoslednjegPrimljenogMTNaloga.Banka b : getBanka()) {
        		if(b.getNazivBanke().equals(naziv))
        			return b;
        	}
        	return null;
        } 


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="nazivBanke">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="255"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nazivBanke",
            "brojac",
            "timestamp"
        })
        public static class Banka {

            @XmlElement(required = true)
            protected String nazivBanke;
            protected int brojac;
            @XmlElement(required = true)
            protected String timestamp;

            /**
             * Gets the value of the nazivBanke property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNazivBanke() {
                return nazivBanke;
            }

            /**
             * Sets the value of the nazivBanke property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNazivBanke(String value) {
                this.nazivBanke = value;
            }

            /**
             * Gets the value of the brojac property.
             * 
             */
            public int getBrojac() {
                return brojac;
            }

            /**
             * Sets the value of the brojac property.
             * 
             */
            public void setBrojac(int value) {
                this.brojac = value;
            }

            /**
             * Gets the value of the timestamp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTimestamp() {
                return timestamp;
            }

            /**
             * Sets the value of the timestamp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTimestamp(String value) {
                this.timestamp = value;
            }

        }

    }

}
