//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 02:40:28 AM CEST 
//


package basexdb.centralna;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.toomanysecrets.centralna package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.toomanysecrets.centralna
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Centralna }
     * 
     */
    public Centralna createCentralna() {
        return new Centralna();
    }

    /**
     * Create an instance of {@link Centralna.BrojacPoslednjegPrimljenogMTNaloga }
     * 
     */
    public Centralna.BrojacPoslednjegPrimljenogMTNaloga createCentralnaBrojacPoslednjegPrimljenogMTNaloga() {
        return new Centralna.BrojacPoslednjegPrimljenogMTNaloga();
    }

    /**
     * Create an instance of {@link Centralna.Banke }
     * 
     */
    public Centralna.Banke createCentralnaBanke() {
        return new Centralna.Banke();
    }

    /**
     * Create an instance of {@link Centralna.BrojacPoslednjegPrimljenogMTNaloga.Banka }
     * 
     */
    public Centralna.BrojacPoslednjegPrimljenogMTNaloga.Banka createCentralnaBrojacPoslednjegPrimljenogMTNalogaBanka() {
        return new Centralna.BrojacPoslednjegPrimljenogMTNaloga.Banka();
    }

    /**
     * Create an instance of {@link Centralna.Banke.Banka }
     * 
     */
    public Centralna.Banke.Banka createCentralnaBankeBanka() {
        return new Centralna.Banke.Banka();
    }

}
