//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.23 at 01:42:45 AM CEST 
//


package beans.presek;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.toomanysecrets.presek package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.toomanysecrets.presek
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Presek }
     * 
     */
    public Presek createPresek() {
        return new Presek();
    }

    /**
     * Create an instance of {@link Presek.Stavke }
     * 
     */
    public Presek.Stavke createPresekStavke() {
        return new Presek.Stavke();
    }

    /**
     * Create an instance of {@link Presek.Zaglavlje }
     * 
     */
    public Presek.Zaglavlje createPresekZaglavlje() {
        return new Presek.Zaglavlje();
    }

    /**
     * Create an instance of {@link Presek.Stavke.Stavka }
     * 
     */
    public Presek.Stavke.Stavka createPresekStavkeStavka() {
        return new Presek.Stavke.Stavka();
    }

}
