<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://www.toomanysecrets.com/MT102Response"
	xmlns:ws="http://www.toomanysecrets.com/MT102Response" xmlns:external="http://www.toomanysecrets.com/mt102"
	xmlns:external1="http://www.toomanysecrets.com/notification"

	name="MT102Response" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
	xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">


	<wsdl:import namespace="http://www.toomanysecrets.com/mt102"
		location="http://localhost:8080/MT102Crypt.xsd" />
	<wsdl:import namespace="http://www.toomanysecrets.com/notification"
		location="http://localhost:8080/NotificationCrypt.xsd" />

	<wsdl:message name="MT102ResponseRequest">
		<wsdl:part name="MT102ResponseReq" element="external:MT102" />
	</wsdl:message>


	<wsdl:message name="notifikacija">
		<wsdl:part name="notif" element="external1:notification" />
	</wsdl:message>


	<wsdl:portType name="MT102ResponsePortType">

		<!--request-response -->
		<wsdl:operation name="PrimiMT102Response">
			<wsdl:input name="MT102ResponseInput" message="ws:MT102ResponseRequest" />
			<wsdl:output name="strOutput" message="ws:notifikacija" />
		</wsdl:operation>


	</wsdl:portType>

	<wsdl:binding name="MT102ResponseBinding" type="ws:MT102ResponsePortType">

		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="document" />

		<wsdl:operation name="PrimiMT102Response">

			<soap:operation soapAction="" style="document" />

			<wsdl:input name="MT102ResponseInput">
				<soap:body use="literal" />
			</wsdl:input>

			<wsdl:output name="strOutput">
				<soap:body use="literal" />
			</wsdl:output>


		</wsdl:operation>

	</wsdl:binding>



	<wsdl:service name="MT102Response">

		<wsdl:port name="MT102ResponsePort" binding="ws:MT102ResponseBinding">
			<soap:address location="http://localhost:8080/MT102ResponsePort" />
		</wsdl:port>

	</wsdl:service>


</wsdl:definitions>