//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.23 at 06:25:52 AM CEST 
//


package basexdb.firma;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import beans.faktura.Faktura;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="informacijeOFirmi">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="naziv">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="pib">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="11"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="adresa">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="informacijeOBankama">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="banka">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="swift">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;pattern value="[A-Z]{4}[A-Z]{2}[0-9A-Z]{2}([0-9A-Z]{3})?"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="brojRacuna">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;pattern value="[0-9]{3}[0-9]{13}[0-9]{2}"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="placeneFakture">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.toomanysecrets.com/faktura}faktura"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="neplaceneFakture">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.toomanysecrets.com/faktura}faktura"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="brojacPoslednjePoslateFakture" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="brojacPoslednjegPoslatogNaloga" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="brojacPoslednjegZahtevaZaIzvod" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="brojacPoslednjePoslateNotifikacije" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="brojacPoslednjePrimljeneFakture" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="firma" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="nazivFirme">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="255"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="brojacPoslednjegPrimljenogPreseka" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="banka" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="nazivBanke">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="255"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="brojacPoslednjePrimljeneNotifikacije" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="banka" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="nazivBanke">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="255"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="firma" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="nazivFirme">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="255"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "informacijeOFirmi",
    "informacijeOBankama",
    "placeneFakture",
    "neplaceneFakture",
    "brojacPoslednjePoslateFakture",
    "brojacPoslednjegPoslatogNaloga",
    "brojacPoslednjegZahtevaZaIzvod",
    "brojacPoslednjePoslateNotifikacije",
    "brojacPoslednjePrimljeneFakture",
    "brojacPoslednjegPrimljenogPreseka",
    "brojacPoslednjePrimljeneNotifikacije"
})
@XmlRootElement(name = "firmeSema")
public class FirmeSema {

    @XmlElement(required = true)
    protected FirmeSema.InformacijeOFirmi informacijeOFirmi;
    @XmlElement(required = true)
    protected FirmeSema.InformacijeOBankama informacijeOBankama;
    @XmlElement(required = true)
    protected FirmeSema.PlaceneFakture placeneFakture;
    @XmlElement(required = true)
    protected FirmeSema.NeplaceneFakture neplaceneFakture = new FirmeSema.NeplaceneFakture();
    protected Integer brojacPoslednjePoslateFakture;
    protected Integer brojacPoslednjegPoslatogNaloga;
    protected Integer brojacPoslednjegZahtevaZaIzvod;
    protected Integer brojacPoslednjePoslateNotifikacije;
    protected FirmeSema.BrojacPoslednjePrimljeneFakture brojacPoslednjePrimljeneFakture;
    protected FirmeSema.BrojacPoslednjegPrimljenogPreseka brojacPoslednjegPrimljenogPreseka;
    protected FirmeSema.BrojacPoslednjePrimljeneNotifikacije brojacPoslednjePrimljeneNotifikacije;

    /**
     * Gets the value of the informacijeOFirmi property.
     * 
     * @return
     *     possible object is
     *     {@link FirmeSema.InformacijeOFirmi }
     *     
     */
    public FirmeSema.InformacijeOFirmi getInformacijeOFirmi() {
        return informacijeOFirmi;
    }

    /**
     * Sets the value of the informacijeOFirmi property.
     * 
     * @param value
     *     allowed object is
     *     {@link FirmeSema.InformacijeOFirmi }
     *     
     */
    public void setInformacijeOFirmi(FirmeSema.InformacijeOFirmi value) {
        this.informacijeOFirmi = value;
    }

    /**
     * Gets the value of the informacijeOBankama property.
     * 
     * @return
     *     possible object is
     *     {@link FirmeSema.InformacijeOBankama }
     *     
     */
    public FirmeSema.InformacijeOBankama getInformacijeOBankama() {
        return informacijeOBankama;
    }

    /**
     * Sets the value of the informacijeOBankama property.
     * 
     * @param value
     *     allowed object is
     *     {@link FirmeSema.InformacijeOBankama }
     *     
     */
    public void setInformacijeOBankama(FirmeSema.InformacijeOBankama value) {
        this.informacijeOBankama = value;
    }

    /**
     * Gets the value of the placeneFakture property.
     * 
     * @return
     *     possible object is
     *     {@link FirmeSema.PlaceneFakture }
     *     
     */
    public FirmeSema.PlaceneFakture getPlaceneFakture() {
        return placeneFakture;
    }

    /**
     * Sets the value of the placeneFakture property.
     * 
     * @param value
     *     allowed object is
     *     {@link FirmeSema.PlaceneFakture }
     *     
     */
    public void setPlaceneFakture(FirmeSema.PlaceneFakture value) {
        this.placeneFakture = value;
    }

    /**
     * Gets the value of the neplaceneFakture property.
     * 
     * @return
     *     possible object is
     *     {@link FirmeSema.NeplaceneFakture }
     *     
     */
    public FirmeSema.NeplaceneFakture getNeplaceneFakture() {
        return neplaceneFakture;
    }

    /**
     * Sets the value of the neplaceneFakture property.
     * 
     * @param value
     *     allowed object is
     *     {@link FirmeSema.NeplaceneFakture }
     *     
     */
    public void setNeplaceneFakture(FirmeSema.NeplaceneFakture value) {
        this.neplaceneFakture = value;
    }

    /**
     * Gets the value of the brojacPoslednjePoslateFakture property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBrojacPoslednjePoslateFakture() {
        return brojacPoslednjePoslateFakture;
    }

    /**
     * Sets the value of the brojacPoslednjePoslateFakture property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBrojacPoslednjePoslateFakture(Integer value) {
        this.brojacPoslednjePoslateFakture = value;
    }

    /**
     * Gets the value of the brojacPoslednjegPoslatogNaloga property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBrojacPoslednjegPoslatogNaloga() {
        return brojacPoslednjegPoslatogNaloga;
    }

    /**
     * Sets the value of the brojacPoslednjegPoslatogNaloga property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBrojacPoslednjegPoslatogNaloga(Integer value) {
        this.brojacPoslednjegPoslatogNaloga = value;
    }

    /**
     * Gets the value of the brojacPoslednjegZahtevaZaIzvod property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBrojacPoslednjegZahtevaZaIzvod() {
        return brojacPoslednjegZahtevaZaIzvod;
    }

    /**
     * Sets the value of the brojacPoslednjegZahtevaZaIzvod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBrojacPoslednjegZahtevaZaIzvod(Integer value) {
        this.brojacPoslednjegZahtevaZaIzvod = value;
    }

    /**
     * Gets the value of the brojacPoslednjePoslateNotifikacije property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBrojacPoslednjePoslateNotifikacije() {
        return brojacPoslednjePoslateNotifikacije;
    }

    /**
     * Sets the value of the brojacPoslednjePoslateNotifikacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBrojacPoslednjePoslateNotifikacije(Integer value) {
        this.brojacPoslednjePoslateNotifikacije = value;
    }

    /**
     * Gets the value of the brojacPoslednjePrimljeneFakture property.
     * 
     * @return
     *     possible object is
     *     {@link FirmeSema.BrojacPoslednjePrimljeneFakture }
     *     
     */
    public FirmeSema.BrojacPoslednjePrimljeneFakture getBrojacPoslednjePrimljeneFakture() {
        return brojacPoslednjePrimljeneFakture;
    }

    /**
     * Sets the value of the brojacPoslednjePrimljeneFakture property.
     * 
     * @param value
     *     allowed object is
     *     {@link FirmeSema.BrojacPoslednjePrimljeneFakture }
     *     
     */
    public void setBrojacPoslednjePrimljeneFakture(FirmeSema.BrojacPoslednjePrimljeneFakture value) {
        this.brojacPoslednjePrimljeneFakture = value;
    }

    /**
     * Gets the value of the brojacPoslednjegPrimljenogPreseka property.
     * 
     * @return
     *     possible object is
     *     {@link FirmeSema.BrojacPoslednjegPrimljenogPreseka }
     *     
     */
    public FirmeSema.BrojacPoslednjegPrimljenogPreseka getBrojacPoslednjegPrimljenogPreseka() {
        return brojacPoslednjegPrimljenogPreseka;
    }

    /**
     * Sets the value of the brojacPoslednjegPrimljenogPreseka property.
     * 
     * @param value
     *     allowed object is
     *     {@link FirmeSema.BrojacPoslednjegPrimljenogPreseka }
     *     
     */
    public void setBrojacPoslednjegPrimljenogPreseka(FirmeSema.BrojacPoslednjegPrimljenogPreseka value) {
        this.brojacPoslednjegPrimljenogPreseka = value;
    }

    /**
     * Gets the value of the brojacPoslednjePrimljeneNotifikacije property.
     * 
     * @return
     *     possible object is
     *     {@link FirmeSema.BrojacPoslednjePrimljeneNotifikacije }
     *     
     */
    public FirmeSema.BrojacPoslednjePrimljeneNotifikacije getBrojacPoslednjePrimljeneNotifikacije() {
        return brojacPoslednjePrimljeneNotifikacije;
    }

    /**
     * Sets the value of the brojacPoslednjePrimljeneNotifikacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link FirmeSema.BrojacPoslednjePrimljeneNotifikacije }
     *     
     */
    public void setBrojacPoslednjePrimljeneNotifikacije(FirmeSema.BrojacPoslednjePrimljeneNotifikacije value) {
        this.brojacPoslednjePrimljeneNotifikacije = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="firma" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="nazivFirme">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="255"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "firma"
    })
    public static class BrojacPoslednjePrimljeneFakture {

        protected List<FirmeSema.BrojacPoslednjePrimljeneFakture.Firma> firma;

        /**
         * Gets the value of the firma property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the firma property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFirma().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FirmeSema.BrojacPoslednjePrimljeneFakture.Firma }
         * 
         * 
         */
        public List<FirmeSema.BrojacPoslednjePrimljeneFakture.Firma> getFirma() {
            if (firma == null) {
                firma = new ArrayList<FirmeSema.BrojacPoslednjePrimljeneFakture.Firma>();
            }
            return this.firma;
        }
        
        public FirmeSema.BrojacPoslednjePrimljeneFakture.Firma getFirmaByNaziv(String naziv) {
        	for(FirmeSema.BrojacPoslednjePrimljeneFakture.Firma f : getFirma()) {
        		if(f.getNazivFirme().equals(naziv))
        			return f;
        	}
        	return null;
        } 


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="nazivFirme">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="255"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nazivFirme",
            "brojac",
            "timestamp"
        })
        public static class Firma {

            @XmlElement(required = true)
            protected String nazivFirme;
            protected int brojac;
            @XmlElement(required = true)
            protected String timestamp;

            /**
             * Gets the value of the nazivFirme property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNazivFirme() {
                return nazivFirme;
            }

            /**
             * Sets the value of the nazivFirme property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNazivFirme(String value) {
                this.nazivFirme = value;
            }

            /**
             * Gets the value of the brojac property.
             * 
             */
            public int getBrojac() {
                return brojac;
            }

            /**
             * Sets the value of the brojac property.
             * 
             */
            public void setBrojac(int value) {
                this.brojac = value;
            }

            /**
             * Gets the value of the timestamp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTimestamp() {
                return timestamp;
            }

            /**
             * Sets the value of the timestamp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTimestamp(String value) {
                this.timestamp = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="banka" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="nazivBanke">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="255"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="firma" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="nazivFirme">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="255"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "banka",
        "firma"
    })
    public static class BrojacPoslednjePrimljeneNotifikacije {

        protected List<FirmeSema.BrojacPoslednjePrimljeneNotifikacije.Banka> banka;
        protected List<FirmeSema.BrojacPoslednjePrimljeneNotifikacije.Firma> firma;

        /**
         * Gets the value of the banka property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the banka property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBanka().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FirmeSema.BrojacPoslednjePrimljeneNotifikacije.Banka }
         * 
         * 
         */
        public List<FirmeSema.BrojacPoslednjePrimljeneNotifikacije.Banka> getBanka() {
            if (banka == null) {
                banka = new ArrayList<FirmeSema.BrojacPoslednjePrimljeneNotifikacije.Banka>();
            }
            return this.banka;
        }
        
        public FirmeSema.BrojacPoslednjePrimljeneNotifikacije.Banka getBankaByNaziv(String naziv) {
        	for(FirmeSema.BrojacPoslednjePrimljeneNotifikacije.Banka b : getBanka()) {
        		if(b.getNazivBanke().equals(naziv))
        			return b;
        	}
        	return null;
        }

        /**
         * Gets the value of the firma property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the firma property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFirma().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FirmeSema.BrojacPoslednjePrimljeneNotifikacije.Firma }
         * 
         * 
         */
        public List<FirmeSema.BrojacPoslednjePrimljeneNotifikacije.Firma> getFirma() {
            if (firma == null) {
                firma = new ArrayList<FirmeSema.BrojacPoslednjePrimljeneNotifikacije.Firma>();
            }
            return this.firma;
        }
        
        public FirmeSema.BrojacPoslednjePrimljeneNotifikacije.Firma getFirmaByNaziv(String naziv) {
        	for(FirmeSema.BrojacPoslednjePrimljeneNotifikacije.Firma f : getFirma()) {
        		if(f.getNazivFirme().equals(naziv))
        			return f;
        	}
        	return null;
        } 


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="nazivBanke">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="255"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nazivBanke",
            "brojac",
            "timestamp"
        })
        public static class Banka {

            @XmlElement(required = true)
            protected String nazivBanke;
            protected int brojac;
            @XmlElement(required = true)
            protected String timestamp;

            /**
             * Gets the value of the nazivBanke property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNazivBanke() {
                return nazivBanke;
            }

            /**
             * Sets the value of the nazivBanke property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNazivBanke(String value) {
                this.nazivBanke = value;
            }

            /**
             * Gets the value of the brojac property.
             * 
             */
            public int getBrojac() {
                return brojac;
            }

            /**
             * Sets the value of the brojac property.
             * 
             */
            public void setBrojac(int value) {
                this.brojac = value;
            }

            /**
             * Gets the value of the timestamp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTimestamp() {
                return timestamp;
            }

            /**
             * Sets the value of the timestamp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTimestamp(String value) {
                this.timestamp = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="nazivFirme">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="255"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nazivFirme",
            "brojac",
            "timestamp"
        })
        public static class Firma {

            @XmlElement(required = true)
            protected String nazivFirme;
            protected int brojac;
            @XmlElement(required = true)
            protected String timestamp;

            /**
             * Gets the value of the nazivFirme property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNazivFirme() {
                return nazivFirme;
            }

            /**
             * Sets the value of the nazivFirme property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNazivFirme(String value) {
                this.nazivFirme = value;
            }

            /**
             * Gets the value of the brojac property.
             * 
             */
            public int getBrojac() {
                return brojac;
            }

            /**
             * Sets the value of the brojac property.
             * 
             */
            public void setBrojac(int value) {
                this.brojac = value;
            }

            /**
             * Gets the value of the timestamp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTimestamp() {
                return timestamp;
            }

            /**
             * Sets the value of the timestamp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTimestamp(String value) {
                this.timestamp = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="banka" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="nazivBanke">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="255"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "banka"
    })
    public static class BrojacPoslednjegPrimljenogPreseka {

        protected List<FirmeSema.BrojacPoslednjegPrimljenogPreseka.Banka> banka;

        /**
         * Gets the value of the banka property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the banka property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBanka().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FirmeSema.BrojacPoslednjegPrimljenogPreseka.Banka }
         * 
         * 
         */
        public List<FirmeSema.BrojacPoslednjegPrimljenogPreseka.Banka> getBanka() {
            if (banka == null) {
                banka = new ArrayList<FirmeSema.BrojacPoslednjegPrimljenogPreseka.Banka>();
            }
            return this.banka;
        }
        
        
        public FirmeSema.BrojacPoslednjegPrimljenogPreseka.Banka getBankaByNaziv(String naziv) {
        	for(FirmeSema.BrojacPoslednjegPrimljenogPreseka.Banka b : getBanka()) {
        		if(b.getNazivBanke().equals(naziv))
        			return b;
        	}
        	return null;
        } 


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="nazivBanke">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="255"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nazivBanke",
            "brojac",
            "timestamp"
        })
        public static class Banka {

            @XmlElement(required = true)
            protected String nazivBanke;
            protected int brojac;
            @XmlElement(required = true)
            protected String timestamp;

            /**
             * Gets the value of the nazivBanke property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNazivBanke() {
                return nazivBanke;
            }

            /**
             * Sets the value of the nazivBanke property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNazivBanke(String value) {
                this.nazivBanke = value;
            }

            /**
             * Gets the value of the brojac property.
             * 
             */
            public int getBrojac() {
                return brojac;
            }

            /**
             * Sets the value of the brojac property.
             * 
             */
            public void setBrojac(int value) {
                this.brojac = value;
            }

            /**
             * Gets the value of the timestamp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTimestamp() {
                return timestamp;
            }

            /**
             * Sets the value of the timestamp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTimestamp(String value) {
                this.timestamp = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="banka">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="swift">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;pattern value="[A-Z]{4}[A-Z]{2}[0-9A-Z]{2}([0-9A-Z]{3})?"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="brojRacuna">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;pattern value="[0-9]{3}[0-9]{13}[0-9]{2}"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "banka"
    })
    public static class InformacijeOBankama {

        @XmlElement(required = true)
        protected List<FirmeSema.InformacijeOBankama.Banka> banka;

        /**
         * Gets the value of the banka property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the banka property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBanka().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FirmeSema.InformacijeOBankama.Banka }
         * 
         * 
         */
        public List<FirmeSema.InformacijeOBankama.Banka> getBanka() {
            if (banka == null) {
                banka = new ArrayList<FirmeSema.InformacijeOBankama.Banka>();
            }
            return this.banka;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="swift">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;pattern value="[A-Z]{4}[A-Z]{2}[0-9A-Z]{2}([0-9A-Z]{3})?"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="brojRacuna">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;pattern value="[0-9]{3}[0-9]{13}[0-9]{2}"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "naziv",
            "swift",
            "brojRacuna"
        })
        public static class Banka {

            @XmlElement(required = true)
            protected String naziv;
            @XmlElement(required = true)
            protected String swift;
            @XmlElement(required = true)
            protected String brojRacuna;

            /**
             * Gets the value of the naziv property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNaziv() {
                return naziv;
            }

            /**
             * Sets the value of the naziv property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNaziv(String value) {
                this.naziv = value;
            }

            /**
             * Gets the value of the swift property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSwift() {
                return swift;
            }

            /**
             * Sets the value of the swift property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSwift(String value) {
                this.swift = value;
            }

            /**
             * Gets the value of the brojRacuna property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBrojRacuna() {
                return brojRacuna;
            }

            /**
             * Sets the value of the brojRacuna property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBrojRacuna(String value) {
                this.brojRacuna = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="naziv">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="pib">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="11"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="adresa">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naziv",
        "pib",
        "adresa"
    })
    public static class InformacijeOFirmi {

        @XmlElement(required = true)
        protected String naziv;
        @XmlElement(required = true)
        protected String pib;
        @XmlElement(required = true)
        protected String adresa;

        /**
         * Gets the value of the naziv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaziv() {
            return naziv;
        }

        /**
         * Sets the value of the naziv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaziv(String value) {
            this.naziv = value;
        }

        /**
         * Gets the value of the pib property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPib() {
            return pib;
        }

        /**
         * Sets the value of the pib property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPib(String value) {
            this.pib = value;
        }

        /**
         * Gets the value of the adresa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdresa(String value) {
            this.adresa = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.toomanysecrets.com/faktura}faktura"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "faktura"
    })
    public static class NeplaceneFakture {

        @XmlElement(namespace = "http://www.toomanysecrets.com/faktura")
        protected List<Faktura> faktura;

        /**
         * Gets the value of the faktura property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the faktura property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFaktura().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Faktura }
         * 
         * 
         */
        public List<Faktura> getFaktura() {
            if (faktura == null) {
                faktura = new ArrayList<Faktura>();
            }
            return this.faktura;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.toomanysecrets.com/faktura}faktura"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "faktura"
    })
    public static class PlaceneFakture {

        @XmlElement(namespace = "http://www.toomanysecrets.com/faktura")
        protected List<Faktura> faktura;

        /**
         * Gets the value of the faktura property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the faktura property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFaktura().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Faktura }
         * 
         * 
         */
        public List<Faktura> getFaktura() {
            if (faktura == null) {
                faktura = new ArrayList<Faktura>();
            }
            return this.faktura;
        }

    }

}
