//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.23 at 06:25:52 AM CEST 
//


package basexdb.firma;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.toomanysecrets.firmesema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.toomanysecrets.firmesema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FirmeSema }
     * 
     */
    public FirmeSema createFirmeSema() {
        return new FirmeSema();
    }

    /**
     * Create an instance of {@link FirmeSema.BrojacPoslednjePrimljeneNotifikacije }
     * 
     */
    public FirmeSema.BrojacPoslednjePrimljeneNotifikacije createFirmeSemaBrojacPoslednjePrimljeneNotifikacije() {
        return new FirmeSema.BrojacPoslednjePrimljeneNotifikacije();
    }

    /**
     * Create an instance of {@link FirmeSema.BrojacPoslednjegPrimljenogPreseka }
     * 
     */
    public FirmeSema.BrojacPoslednjegPrimljenogPreseka createFirmeSemaBrojacPoslednjegPrimljenogPreseka() {
        return new FirmeSema.BrojacPoslednjegPrimljenogPreseka();
    }

    /**
     * Create an instance of {@link FirmeSema.BrojacPoslednjePrimljeneFakture }
     * 
     */
    public FirmeSema.BrojacPoslednjePrimljeneFakture createFirmeSemaBrojacPoslednjePrimljeneFakture() {
        return new FirmeSema.BrojacPoslednjePrimljeneFakture();
    }

    /**
     * Create an instance of {@link FirmeSema.InformacijeOBankama }
     * 
     */
    public FirmeSema.InformacijeOBankama createFirmeSemaInformacijeOBankama() {
        return new FirmeSema.InformacijeOBankama();
    }

    /**
     * Create an instance of {@link FirmeSema.InformacijeOFirmi }
     * 
     */
    public FirmeSema.InformacijeOFirmi createFirmeSemaInformacijeOFirmi() {
        return new FirmeSema.InformacijeOFirmi();
    }

    /**
     * Create an instance of {@link FirmeSema.PlaceneFakture }
     * 
     */
    public FirmeSema.PlaceneFakture createFirmeSemaPlaceneFakture() {
        return new FirmeSema.PlaceneFakture();
    }

    /**
     * Create an instance of {@link FirmeSema.NeplaceneFakture }
     * 
     */
    public FirmeSema.NeplaceneFakture createFirmeSemaNeplaceneFakture() {
        return new FirmeSema.NeplaceneFakture();
    }

    /**
     * Create an instance of {@link FirmeSema.BrojacPoslednjePrimljeneNotifikacije.Banka }
     * 
     */
    public FirmeSema.BrojacPoslednjePrimljeneNotifikacije.Banka createFirmeSemaBrojacPoslednjePrimljeneNotifikacijeBanka() {
        return new FirmeSema.BrojacPoslednjePrimljeneNotifikacije.Banka();
    }

    /**
     * Create an instance of {@link FirmeSema.BrojacPoslednjePrimljeneNotifikacije.Firma }
     * 
     */
    public FirmeSema.BrojacPoslednjePrimljeneNotifikacije.Firma createFirmeSemaBrojacPoslednjePrimljeneNotifikacijeFirma() {
        return new FirmeSema.BrojacPoslednjePrimljeneNotifikacije.Firma();
    }

    /**
     * Create an instance of {@link FirmeSema.BrojacPoslednjegPrimljenogPreseka.Banka }
     * 
     */
    public FirmeSema.BrojacPoslednjegPrimljenogPreseka.Banka createFirmeSemaBrojacPoslednjegPrimljenogPresekaBanka() {
        return new FirmeSema.BrojacPoslednjegPrimljenogPreseka.Banka();
    }

    /**
     * Create an instance of {@link FirmeSema.BrojacPoslednjePrimljeneFakture.Firma }
     * 
     */
    public FirmeSema.BrojacPoslednjePrimljeneFakture.Firma createFirmeSemaBrojacPoslednjePrimljeneFaktureFirma() {
        return new FirmeSema.BrojacPoslednjePrimljeneFakture.Firma();
    }

    /**
     * Create an instance of {@link FirmeSema.InformacijeOBankama.Banka }
     * 
     */
    public FirmeSema.InformacijeOBankama.Banka createFirmeSemaInformacijeOBankamaBanka() {
        return new FirmeSema.InformacijeOBankama.Banka();
    }

}
