//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.24 at 06:50:45 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.toomanysecrets.com/firmesema")
package basexdb.firma;
