//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.24 at 04:50:14 PM CEST 
//


package util.accessControl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the util.accessControl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: util.accessControl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TRola }
     * 
     */
    public TRola createTRola() {
        return new TRola();
    }

    /**
     * Create an instance of {@link Korisnici }
     * 
     */
    public Korisnici createKorisnici() {
        return new Korisnici();
    }

    /**
     * Create an instance of {@link TKorisnik }
     * 
     */
    public TKorisnik createTKorisnik() {
        return new TKorisnik();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link util.accessControl.Akcije }
     * 
     */
    public util.accessControl.Akcije createAkcije() {
        return new util.accessControl.Akcije();
    }

    /**
     * Create an instance of {@link TAkcija }
     * 
     */
    public TAkcija createTAkcija() {
        return new TAkcija();
    }

    /**
     * Create an instance of {@link TRola.Akcije }
     * 
     */
    public TRola.Akcije createTRolaAkcije() {
        return new TRola.Akcije();
    }

}
