//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.29 at 03:26:05 PM CEST 
//


package beans.mt102;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zaglavljeMT102">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="swiftBankeDuznika">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="8"/>
 *                         &lt;maxLength value="11"/>
 *                         &lt;pattern value="[A-Z]{4}[A-Z]{2}[0-9A-Z]{2}([0-9A-Z]{3})?"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="obracunskiRacunBankeDuzinka">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="18"/>
 *                         &lt;pattern value="[0-9]{3}[0-9]{13}[0-9]{2}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="swiftBankePoverioca">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="8"/>
 *                         &lt;maxLength value="11"/>
 *                         &lt;pattern value="[A-Z]{4}[A-Z]{2}[0-9A-Z]{2}([0-9A-Z]{3})?"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="obracunskiRacunBankePoverioca">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="18"/>
 *                         &lt;pattern value="[0-9]{3}[0-9]{13}[0-9]{2}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ukupanIznos">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;totalDigits value="15"/>
 *                         &lt;fractionDigits value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="sifraValute">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="datumValute">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *                         &lt;minInclusive value="1900-01-01"/>
 *                         &lt;maxInclusive value="2200-01-01"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="datum">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *                         &lt;minInclusive value="1900-01-01"/>
 *                         &lt;maxInclusive value="2200-01-01"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="idPoruke" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;maxLength value="50"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="pojedinacnaUplata" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="duznik">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="svrhaUplate">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="primalac">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="datumNaloga">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *                         &lt;minInclusive value="1900-01-01"/>
 *                         &lt;maxInclusive value="2200-01-01"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="racunDuznika">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="18"/>
 *                         &lt;pattern value="[0-9]{3}[0-9]{13}[0-9]{2}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="modelZaduzenja">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;totalDigits value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="pozivNaBrojZaduzenja">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="20"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="racunPoverioca">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="18"/>
 *                         &lt;pattern value="[0-9]{3}[0-9]{13}[0-9]{2}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="modelOdobrenja">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;totalDigits value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="pozivNaBrojOdobrenja">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="20"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="iznos">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;totalDigits value="15"/>
 *                         &lt;fractionDigits value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="sifraValute">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="idNamogaLzaPlacanje" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;maxLength value="50"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zaglavljeMT102",
    "pojedinacnaUplata"
})
@XmlRootElement(name = "MT102")
public class MT102 {

    @XmlElement(required = true)
    protected MT102 .ZaglavljeMT102 zaglavljeMT102;
    @XmlElement(required = true)
    protected List<MT102 .PojedinacnaUplata> pojedinacnaUplata;

    /**
     * Gets the value of the zaglavljeMT102 property.
     * 
     * @return
     *     possible object is
     *     {@link MT102 .ZaglavljeMT102 }
     *     
     */
    public MT102 .ZaglavljeMT102 getZaglavljeMT102() {
        return zaglavljeMT102;
    }

    /**
     * Sets the value of the zaglavljeMT102 property.
     * 
     * @param value
     *     allowed object is
     *     {@link MT102 .ZaglavljeMT102 }
     *     
     */
    public void setZaglavljeMT102(MT102 .ZaglavljeMT102 value) {
        this.zaglavljeMT102 = value;
    }

    /**
     * Gets the value of the pojedinacnaUplata property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pojedinacnaUplata property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPojedinacnaUplata().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MT102 .PojedinacnaUplata }
     * 
     * 
     */
    public List<MT102 .PojedinacnaUplata> getPojedinacnaUplata() {
        if (pojedinacnaUplata == null) {
            pojedinacnaUplata = new ArrayList<MT102 .PojedinacnaUplata>();
        }
        return this.pojedinacnaUplata;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="duznik">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="svrhaUplate">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="primalac">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="datumNaloga">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
     *               &lt;minInclusive value="1900-01-01"/>
     *               &lt;maxInclusive value="2200-01-01"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="racunDuznika">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="18"/>
     *               &lt;pattern value="[0-9]{3}[0-9]{13}[0-9]{2}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="modelZaduzenja">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *               &lt;minInclusive value="0"/>
     *               &lt;totalDigits value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="pozivNaBrojZaduzenja">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="racunPoverioca">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="18"/>
     *               &lt;pattern value="[0-9]{3}[0-9]{13}[0-9]{2}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="modelOdobrenja">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *               &lt;minInclusive value="0"/>
     *               &lt;totalDigits value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="pozivNaBrojOdobrenja">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="iznos">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;totalDigits value="15"/>
     *               &lt;fractionDigits value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="sifraValute">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="3"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="idNamogaLzaPlacanje" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;maxLength value="50"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "duznik",
        "svrhaUplate",
        "primalac",
        "datumNaloga",
        "racunDuznika",
        "modelZaduzenja",
        "pozivNaBrojZaduzenja",
        "racunPoverioca",
        "modelOdobrenja",
        "pozivNaBrojOdobrenja",
        "iznos",
        "sifraValute"
    })
    public static class PojedinacnaUplata {

        @XmlElement(required = true)
        protected String duznik;
        @XmlElement(required = true)
        protected String svrhaUplate;
        @XmlElement(required = true)
        protected String primalac;
        @XmlElement(required = true, type = String.class)
        @XmlJavaTypeAdapter(Adapter1 .class)
        protected Date datumNaloga;
        @XmlElement(required = true)
        protected String racunDuznika;
        protected int modelZaduzenja;
        @XmlElement(required = true)
        protected String pozivNaBrojZaduzenja;
        @XmlElement(required = true)
        protected String racunPoverioca;
        protected int modelOdobrenja;
        @XmlElement(required = true)
        protected String pozivNaBrojOdobrenja;
        @XmlElement(required = true)
        protected BigDecimal iznos;
        @XmlElement(required = true)
        protected String sifraValute;
        @XmlAttribute(name = "idNamogaLzaPlacanje", required = true)
        protected String idNamogaLzaPlacanje;

        /**
         * Gets the value of the duznik property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDuznik() {
            return duznik;
        }

        /**
         * Sets the value of the duznik property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDuznik(String value) {
            this.duznik = value;
        }

        /**
         * Gets the value of the svrhaUplate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSvrhaUplate() {
            return svrhaUplate;
        }

        /**
         * Sets the value of the svrhaUplate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSvrhaUplate(String value) {
            this.svrhaUplate = value;
        }

        /**
         * Gets the value of the primalac property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrimalac() {
            return primalac;
        }

        /**
         * Sets the value of the primalac property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrimalac(String value) {
            this.primalac = value;
        }

        /**
         * Gets the value of the datumNaloga property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Date getDatumNaloga() {
            return datumNaloga;
        }

        /**
         * Sets the value of the datumNaloga property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatumNaloga(Date value) {
            this.datumNaloga = value;
        }

        /**
         * Gets the value of the racunDuznika property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRacunDuznika() {
            return racunDuznika;
        }

        /**
         * Sets the value of the racunDuznika property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRacunDuznika(String value) {
            this.racunDuznika = value;
        }

        /**
         * Gets the value of the modelZaduzenja property.
         * 
         */
        public int getModelZaduzenja() {
            return modelZaduzenja;
        }

        /**
         * Sets the value of the modelZaduzenja property.
         * 
         */
        public void setModelZaduzenja(int value) {
            this.modelZaduzenja = value;
        }

        /**
         * Gets the value of the pozivNaBrojZaduzenja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPozivNaBrojZaduzenja() {
            return pozivNaBrojZaduzenja;
        }

        /**
         * Sets the value of the pozivNaBrojZaduzenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPozivNaBrojZaduzenja(String value) {
            this.pozivNaBrojZaduzenja = value;
        }

        /**
         * Gets the value of the racunPoverioca property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRacunPoverioca() {
            return racunPoverioca;
        }

        /**
         * Sets the value of the racunPoverioca property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRacunPoverioca(String value) {
            this.racunPoverioca = value;
        }

        /**
         * Gets the value of the modelOdobrenja property.
         * 
         */
        public int getModelOdobrenja() {
            return modelOdobrenja;
        }

        /**
         * Sets the value of the modelOdobrenja property.
         * 
         */
        public void setModelOdobrenja(int value) {
            this.modelOdobrenja = value;
        }

        /**
         * Gets the value of the pozivNaBrojOdobrenja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPozivNaBrojOdobrenja() {
            return pozivNaBrojOdobrenja;
        }

        /**
         * Sets the value of the pozivNaBrojOdobrenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPozivNaBrojOdobrenja(String value) {
            this.pozivNaBrojOdobrenja = value;
        }

        /**
         * Gets the value of the iznos property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getIznos() {
            return iznos;
        }

        /**
         * Sets the value of the iznos property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setIznos(BigDecimal value) {
            this.iznos = value;
        }

        /**
         * Gets the value of the sifraValute property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSifraValute() {
            return sifraValute;
        }

        /**
         * Sets the value of the sifraValute property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSifraValute(String value) {
            this.sifraValute = value;
        }

        /**
         * Gets the value of the idNamogaLzaPlacanje property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdNamogaLzaPlacanje() {
            return idNamogaLzaPlacanje;
        }

        /**
         * Sets the value of the idNamogaLzaPlacanje property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdNamogaLzaPlacanje(String value) {
            this.idNamogaLzaPlacanje = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="swiftBankeDuznika">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="8"/>
     *               &lt;maxLength value="11"/>
     *               &lt;pattern value="[A-Z]{4}[A-Z]{2}[0-9A-Z]{2}([0-9A-Z]{3})?"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="obracunskiRacunBankeDuzinka">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="18"/>
     *               &lt;pattern value="[0-9]{3}[0-9]{13}[0-9]{2}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="swiftBankePoverioca">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="8"/>
     *               &lt;maxLength value="11"/>
     *               &lt;pattern value="[A-Z]{4}[A-Z]{2}[0-9A-Z]{2}([0-9A-Z]{3})?"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="obracunskiRacunBankePoverioca">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="18"/>
     *               &lt;pattern value="[0-9]{3}[0-9]{13}[0-9]{2}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ukupanIznos">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;totalDigits value="15"/>
     *               &lt;fractionDigits value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="sifraValute">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="3"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="datumValute">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
     *               &lt;minInclusive value="1900-01-01"/>
     *               &lt;maxInclusive value="2200-01-01"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="datum">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
     *               &lt;minInclusive value="1900-01-01"/>
     *               &lt;maxInclusive value="2200-01-01"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="idPoruke" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;maxLength value="50"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "swiftBankeDuznika",
        "obracunskiRacunBankeDuzinka",
        "swiftBankePoverioca",
        "obracunskiRacunBankePoverioca",
        "ukupanIznos",
        "sifraValute",
        "datumValute",
        "datum"
    })
    public static class ZaglavljeMT102 {

        @XmlElement(required = true)
        protected String swiftBankeDuznika;
        @XmlElement(required = true)
        protected String obracunskiRacunBankeDuzinka;
        @XmlElement(required = true)
        protected String swiftBankePoverioca;
        @XmlElement(required = true)
        protected String obracunskiRacunBankePoverioca;
        @XmlElement(required = true)
        protected BigDecimal ukupanIznos;
        @XmlElement(required = true)
        protected String sifraValute;
        @XmlElement(required = true, type = String.class)
        @XmlJavaTypeAdapter(Adapter2 .class)
        protected Date datumValute;
        @XmlElement(required = true, type = String.class)
        @XmlJavaTypeAdapter(Adapter3 .class)
        protected Date datum;
        @XmlAttribute(name = "idPoruke", required = true)
        protected String idPoruke;

        /**
         * Gets the value of the swiftBankeDuznika property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSwiftBankeDuznika() {
            return swiftBankeDuznika;
        }

        /**
         * Sets the value of the swiftBankeDuznika property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSwiftBankeDuznika(String value) {
            this.swiftBankeDuznika = value;
        }

        /**
         * Gets the value of the obracunskiRacunBankeDuzinka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObracunskiRacunBankeDuzinka() {
            return obracunskiRacunBankeDuzinka;
        }

        /**
         * Sets the value of the obracunskiRacunBankeDuzinka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObracunskiRacunBankeDuzinka(String value) {
            this.obracunskiRacunBankeDuzinka = value;
        }

        /**
         * Gets the value of the swiftBankePoverioca property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSwiftBankePoverioca() {
            return swiftBankePoverioca;
        }

        /**
         * Sets the value of the swiftBankePoverioca property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSwiftBankePoverioca(String value) {
            this.swiftBankePoverioca = value;
        }

        /**
         * Gets the value of the obracunskiRacunBankePoverioca property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObracunskiRacunBankePoverioca() {
            return obracunskiRacunBankePoverioca;
        }

        /**
         * Sets the value of the obracunskiRacunBankePoverioca property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObracunskiRacunBankePoverioca(String value) {
            this.obracunskiRacunBankePoverioca = value;
        }

        /**
         * Gets the value of the ukupanIznos property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getUkupanIznos() {
            return ukupanIznos;
        }

        /**
         * Sets the value of the ukupanIznos property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setUkupanIznos(BigDecimal value) {
            this.ukupanIznos = value;
        }

        /**
         * Gets the value of the sifraValute property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSifraValute() {
            return sifraValute;
        }

        /**
         * Sets the value of the sifraValute property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSifraValute(String value) {
            this.sifraValute = value;
        }

        /**
         * Gets the value of the datumValute property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Date getDatumValute() {
            return datumValute;
        }

        /**
         * Sets the value of the datumValute property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatumValute(Date value) {
            this.datumValute = value;
        }

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Date getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatum(Date value) {
            this.datum = value;
        }

        /**
         * Gets the value of the idPoruke property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdPoruke() {
            return idPoruke;
        }

        /**
         * Sets the value of the idPoruke property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdPoruke(String value) {
            this.idPoruke = value;
        }

    }

}
