//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.25 at 03:18:51 AM CEST 
//


package basexdb.registar;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.toomanysecrets.registar package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.toomanysecrets.registar
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Registar }
     * 
     */
    public Registar createRegistar() {
        return new Registar();
    }

    /**
     * Create an instance of {@link Registar.Firme }
     * 
     */
    public Registar.Firme createRegistarFirme() {
        return new Registar.Firme();
    }

    /**
     * Create an instance of {@link Registar.Firme.Firma }
     * 
     */
    public Registar.Firme.Firma createRegistarFirmeFirma() {
        return new Registar.Firme.Firma();
    }

    /**
     * Create an instance of {@link Registar.Banke }
     * 
     */
    public Registar.Banke createRegistarBanke() {
        return new Registar.Banke();
    }

    /**
     * Create an instance of {@link Registar.Firme.Firma.Racuni }
     * 
     */
    public Registar.Firme.Firma.Racuni createRegistarFirmeFirmaRacuni() {
        return new Registar.Firme.Firma.Racuni();
    }

    /**
     * Create an instance of {@link Registar.Banke.Banka }
     * 
     */
    public Registar.Banke.Banka createRegistarBankeBanka() {
        return new Registar.Banke.Banka();
    }

}
