//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.23 at 11:07:43 PM CEST 
//


package basexdb.banka;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import beans.nalog.Nalog;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="swift">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[A-Z]{4}[A-Z]{2}[0-9A-Z]{2}([0-9A-Z]{3})?"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="adresa">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="obracunskiRacun">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="korisnickiRacuni">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="racun">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="brojRacuna">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;length value="18"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="vlasnik">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="255"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="pib">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="11"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="stanje">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                   &lt;totalDigits value="15"/>
 *                                   &lt;fractionDigits value="2"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="blokiran" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="rezervisano">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                   &lt;totalDigits value="15"/>
 *                                   &lt;fractionDigits value="2"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="realizovaniNalozi">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="realizovanNalog">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.toomanysecrets.com/nalog}nalog"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="nerealizovaniNalozi">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="nerealizovanNalog">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="vrstaNaloga" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element ref="{http://www.toomanysecrets.com/nalog}nalog"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="brojacStavkiZaKliring" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="brojacStavkiZaPresek" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="brojacPoslednjegPoslatogPreseka" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="brojacPoslednjegPoslatogMTNaloga" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="brojacPoslednjePoslateNotifikacije" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="brojacPoslednjePrimljeneNotifikacije" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="centralnabanka" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="brojacPoslednjegPrimljenogNaloga" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="firma" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="nazivFirme">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="255"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="brojacPoslednjegPrimljenogZahtevaZaIzvod" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="firma" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="nazivFirme">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="255"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "swift",
    "adresa",
    "obracunskiRacun",
    "korisnickiRacuni",
    "realizovaniNalozi",
    "nerealizovaniNalozi",
    "brojacStavkiZaKliring",
    "brojacStavkiZaPresek",
    "brojacPoslednjegPoslatogPreseka",
    "brojacPoslednjegPoslatogMTNaloga",
    "brojacPoslednjePoslateNotifikacije",
    "brojacPoslednjePrimljeneNotifikacije",
    "brojacPoslednjegPrimljenogNaloga",
    "brojacPoslednjegPrimljenogZahtevaZaIzvod"
})
@XmlRootElement(name = "bankeSema")
public class BankeSema {

    @XmlElement(required = true)
    protected String swift;
    @XmlElement(required = true)
    protected String adresa;
    @XmlElement(required = true)
    protected String obracunskiRacun;
    @XmlElement(required = true)
    protected BankeSema.KorisnickiRacuni korisnickiRacuni;
    @XmlElement(required = true)
    protected BankeSema.RealizovaniNalozi realizovaniNalozi;
    @XmlElement(required = true)
    protected BankeSema.NerealizovaniNalozi nerealizovaniNalozi;
    protected int brojacStavkiZaKliring;
    protected int brojacStavkiZaPresek = 3;
    protected Integer brojacPoslednjegPoslatogPreseka;
    protected Integer brojacPoslednjegPoslatogMTNaloga;
    protected Integer brojacPoslednjePoslateNotifikacije;
    protected BankeSema.BrojacPoslednjePrimljeneNotifikacije brojacPoslednjePrimljeneNotifikacije;
    protected BankeSema.BrojacPoslednjegPrimljenogNaloga brojacPoslednjegPrimljenogNaloga;
    protected BankeSema.BrojacPoslednjegPrimljenogZahtevaZaIzvod brojacPoslednjegPrimljenogZahtevaZaIzvod;

    /**
     * Gets the value of the swift property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwift() {
        return swift;
    }

    /**
     * Sets the value of the swift property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwift(String value) {
        this.swift = value;
    }

    /**
     * Gets the value of the adresa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresa() {
        return adresa;
    }

    /**
     * Sets the value of the adresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresa(String value) {
        this.adresa = value;
    }

    /**
     * Gets the value of the obracunskiRacun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObracunskiRacun() {
        return obracunskiRacun;
    }

    /**
     * Sets the value of the obracunskiRacun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObracunskiRacun(String value) {
        this.obracunskiRacun = value;
    }

    /**
     * Gets the value of the korisnickiRacuni property.
     * 
     * @return
     *     possible object is
     *     {@link BankeSema.KorisnickiRacuni }
     *     
     */
    public BankeSema.KorisnickiRacuni getKorisnickiRacuni() {
        return korisnickiRacuni;
    }

    /**
     * Sets the value of the korisnickiRacuni property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankeSema.KorisnickiRacuni }
     *     
     */
    public void setKorisnickiRacuni(BankeSema.KorisnickiRacuni value) {
        this.korisnickiRacuni = value;
    }

    /**
     * Gets the value of the realizovaniNalozi property.
     * 
     * @return
     *     possible object is
     *     {@link BankeSema.RealizovaniNalozi }
     *     
     */
    public BankeSema.RealizovaniNalozi getRealizovaniNalozi() {
        return realizovaniNalozi;
    }

    /**
     * Sets the value of the realizovaniNalozi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankeSema.RealizovaniNalozi }
     *     
     */
    public void setRealizovaniNalozi(BankeSema.RealizovaniNalozi value) {
        this.realizovaniNalozi = value;
    }

    /**
     * Gets the value of the nerealizovaniNalozi property.
     * 
     * @return
     *     possible object is
     *     {@link BankeSema.NerealizovaniNalozi }
     *     
     */
    public BankeSema.NerealizovaniNalozi getNerealizovaniNalozi() {
        return nerealizovaniNalozi;
    }

    /**
     * Sets the value of the nerealizovaniNalozi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankeSema.NerealizovaniNalozi }
     *     
     */
    public void setNerealizovaniNalozi(BankeSema.NerealizovaniNalozi value) {
        this.nerealizovaniNalozi = value;
    }

    /**
     * Gets the value of the brojacStavkiZaKliring property.
     * 
     */
    public int getBrojacStavkiZaKliring() {
        return brojacStavkiZaKliring;
    }

    /**
     * Sets the value of the brojacStavkiZaKliring property.
     * 
     */
    public void setBrojacStavkiZaKliring(int value) {
        this.brojacStavkiZaKliring = value;
    }

    /**
     * Gets the value of the brojacStavkiZaPresek property.
     * 
     */
    public int getBrojacStavkiZaPresek() {
        return brojacStavkiZaPresek;
    }

    /**
     * Sets the value of the brojacStavkiZaPresek property.
     * 
     */
    public void setBrojacStavkiZaPresek(int value) {
        this.brojacStavkiZaPresek = value;
    }

    /**
     * Gets the value of the brojacPoslednjegPoslatogPreseka property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBrojacPoslednjegPoslatogPreseka() {
        return brojacPoslednjegPoslatogPreseka;
    }

    /**
     * Sets the value of the brojacPoslednjegPoslatogPreseka property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBrojacPoslednjegPoslatogPreseka(Integer value) {
        this.brojacPoslednjegPoslatogPreseka = value;
    }

    /**
     * Gets the value of the brojacPoslednjegPoslatogMTNaloga property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBrojacPoslednjegPoslatogMTNaloga() {
        return brojacPoslednjegPoslatogMTNaloga;
    }

    /**
     * Sets the value of the brojacPoslednjegPoslatogMTNaloga property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBrojacPoslednjegPoslatogMTNaloga(Integer value) {
        this.brojacPoslednjegPoslatogMTNaloga = value;
    }

    /**
     * Gets the value of the brojacPoslednjePoslateNotifikacije property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBrojacPoslednjePoslateNotifikacije() {
        return brojacPoslednjePoslateNotifikacije;
    }

    /**
     * Sets the value of the brojacPoslednjePoslateNotifikacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBrojacPoslednjePoslateNotifikacije(Integer value) {
        this.brojacPoslednjePoslateNotifikacije = value;
    }

    /**
     * Gets the value of the brojacPoslednjePrimljeneNotifikacije property.
     * 
     * @return
     *     possible object is
     *     {@link BankeSema.BrojacPoslednjePrimljeneNotifikacije }
     *     
     */
    public BankeSema.BrojacPoslednjePrimljeneNotifikacije getBrojacPoslednjePrimljeneNotifikacije() {
        return brojacPoslednjePrimljeneNotifikacije;
    }

    /**
     * Sets the value of the brojacPoslednjePrimljeneNotifikacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankeSema.BrojacPoslednjePrimljeneNotifikacije }
     *     
     */
    public void setBrojacPoslednjePrimljeneNotifikacije(BankeSema.BrojacPoslednjePrimljeneNotifikacije value) {
        this.brojacPoslednjePrimljeneNotifikacije = value;
    }

    /**
     * Gets the value of the brojacPoslednjegPrimljenogNaloga property.
     * 
     * @return
     *     possible object is
     *     {@link BankeSema.BrojacPoslednjegPrimljenogNaloga }
     *     
     */
    public BankeSema.BrojacPoslednjegPrimljenogNaloga getBrojacPoslednjegPrimljenogNaloga() {
        return brojacPoslednjegPrimljenogNaloga;
    }

    /**
     * Sets the value of the brojacPoslednjegPrimljenogNaloga property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankeSema.BrojacPoslednjegPrimljenogNaloga }
     *     
     */
    public void setBrojacPoslednjegPrimljenogNaloga(BankeSema.BrojacPoslednjegPrimljenogNaloga value) {
        this.brojacPoslednjegPrimljenogNaloga = value;
    }

    /**
     * Gets the value of the brojacPoslednjegPrimljenogZahtevaZaIzvod property.
     * 
     * @return
     *     possible object is
     *     {@link BankeSema.BrojacPoslednjegPrimljenogZahtevaZaIzvod }
     *     
     */
    public BankeSema.BrojacPoslednjegPrimljenogZahtevaZaIzvod getBrojacPoslednjegPrimljenogZahtevaZaIzvod() {
        return brojacPoslednjegPrimljenogZahtevaZaIzvod;
    }

    /**
     * Sets the value of the brojacPoslednjegPrimljenogZahtevaZaIzvod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankeSema.BrojacPoslednjegPrimljenogZahtevaZaIzvod }
     *     
     */
    public void setBrojacPoslednjegPrimljenogZahtevaZaIzvod(BankeSema.BrojacPoslednjegPrimljenogZahtevaZaIzvod value) {
        this.brojacPoslednjegPrimljenogZahtevaZaIzvod = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="centralnabanka" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "centralnabanka"
    })
    public static class BrojacPoslednjePrimljeneNotifikacije {

        protected BankeSema.BrojacPoslednjePrimljeneNotifikacije.Centralnabanka centralnabanka;

        /**
         * Gets the value of the centralnabanka property.
         * 
         * @return
         *     possible object is
         *     {@link BankeSema.BrojacPoslednjePrimljeneNotifikacije.Centralnabanka }
         *     
         */
        public BankeSema.BrojacPoslednjePrimljeneNotifikacije.Centralnabanka getCentralnabanka() {
            return centralnabanka;
        }

        /**
         * Sets the value of the centralnabanka property.
         * 
         * @param value
         *     allowed object is
         *     {@link BankeSema.BrojacPoslednjePrimljeneNotifikacije.Centralnabanka }
         *     
         */
        public void setCentralnabanka(BankeSema.BrojacPoslednjePrimljeneNotifikacije.Centralnabanka value) {
            this.centralnabanka = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "brojac",
            "timestamp"
        })
        public static class Centralnabanka {

            protected int brojac;
            @XmlElement(required = true)
            protected String timestamp;

            /**
             * Gets the value of the brojac property.
             * 
             */
            public int getBrojac() {
                return brojac;
            }

            /**
             * Sets the value of the brojac property.
             * 
             */
            public void setBrojac(int value) {
                this.brojac = value;
            }

            /**
             * Gets the value of the timestamp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTimestamp() {
                return timestamp;
            }

            /**
             * Sets the value of the timestamp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTimestamp(String value) {
                this.timestamp = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="firma" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="nazivFirme">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="255"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "firma"
    })
    public static class BrojacPoslednjegPrimljenogNaloga {

        protected List<BankeSema.BrojacPoslednjegPrimljenogNaloga.Firma> firma;

        /**
         * Gets the value of the firma property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the firma property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFirma().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BankeSema.BrojacPoslednjegPrimljenogNaloga.Firma }
         * 
         * 
         */
        public List<BankeSema.BrojacPoslednjegPrimljenogNaloga.Firma> getFirma() {
            if (firma == null) {
                firma = new ArrayList<BankeSema.BrojacPoslednjegPrimljenogNaloga.Firma>();
            }
            return this.firma;
        }
        
        
        public BankeSema.BrojacPoslednjegPrimljenogNaloga.Firma getFirmaByNaziv(String naziv) {
        	for(BankeSema.BrojacPoslednjegPrimljenogNaloga.Firma f : getFirma()) {
        		if(f.getNazivFirme().equals(naziv))
        			return f;
        	}
        	return null;
        } 


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="nazivFirme">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="255"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nazivFirme",
            "brojac",
            "timestamp"
        })
        public static class Firma {

            @XmlElement(required = true)
            protected String nazivFirme;
            protected int brojac;
            @XmlElement(required = true)
            protected String timestamp;

            /**
             * Gets the value of the nazivFirme property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNazivFirme() {
                return nazivFirme;
            }

            /**
             * Sets the value of the nazivFirme property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNazivFirme(String value) {
                this.nazivFirme = value;
            }

            /**
             * Gets the value of the brojac property.
             * 
             */
            public int getBrojac() {
                return brojac;
            }

            /**
             * Sets the value of the brojac property.
             * 
             */
            public void setBrojac(int value) {
                this.brojac = value;
            }

            /**
             * Gets the value of the timestamp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTimestamp() {
                return timestamp;
            }

            /**
             * Sets the value of the timestamp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTimestamp(String value) {
                this.timestamp = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="firma" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="nazivFirme">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="255"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "firma"
    })
    public static class BrojacPoslednjegPrimljenogZahtevaZaIzvod {

        protected List<BankeSema.BrojacPoslednjegPrimljenogZahtevaZaIzvod.Firma> firma;

        /**
         * Gets the value of the firma property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the firma property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFirma().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BankeSema.BrojacPoslednjegPrimljenogZahtevaZaIzvod.Firma }
         * 
         * 
         */
        public List<BankeSema.BrojacPoslednjegPrimljenogZahtevaZaIzvod.Firma> getFirma() {
            if (firma == null) {
                firma = new ArrayList<BankeSema.BrojacPoslednjegPrimljenogZahtevaZaIzvod.Firma>();
            }
            return this.firma;
        }
        
        public BankeSema.BrojacPoslednjegPrimljenogZahtevaZaIzvod.Firma getFirmaByNaziv(String naziv) {
        	for(BankeSema.BrojacPoslednjegPrimljenogZahtevaZaIzvod.Firma f : getFirma()) {
        		if(f.getNazivFirme().equals(naziv))
        			return f;
        	}
        	return null;
        } 


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="nazivFirme">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="255"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="brojac" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nazivFirme",
            "brojac",
            "timestamp"
        })
        public static class Firma {

            @XmlElement(required = true)
            protected String nazivFirme;
            protected int brojac;
            @XmlElement(required = true)
            protected String timestamp;

            /**
             * Gets the value of the nazivFirme property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNazivFirme() {
                return nazivFirme;
            }

            /**
             * Sets the value of the nazivFirme property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNazivFirme(String value) {
                this.nazivFirme = value;
            }

            /**
             * Gets the value of the brojac property.
             * 
             */
            public int getBrojac() {
                return brojac;
            }

            /**
             * Sets the value of the brojac property.
             * 
             */
            public void setBrojac(int value) {
                this.brojac = value;
            }

            /**
             * Gets the value of the timestamp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTimestamp() {
                return timestamp;
            }

            /**
             * Sets the value of the timestamp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTimestamp(String value) {
                this.timestamp = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="racun">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="brojRacuna">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;length value="18"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="vlasnik">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="255"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="pib">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="11"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="stanje">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                         &lt;totalDigits value="15"/>
     *                         &lt;fractionDigits value="2"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="blokiran" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="rezervisano">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                         &lt;totalDigits value="15"/>
     *                         &lt;fractionDigits value="2"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "racun"
    })
    public static class KorisnickiRacuni {

        @XmlElement(required = true)
        protected List<BankeSema.KorisnickiRacuni.Racun> racun;

        /**
         * Gets the value of the racun property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the racun property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRacun().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BankeSema.KorisnickiRacuni.Racun }
         * 
         * 
         */
        public List<BankeSema.KorisnickiRacuni.Racun> getRacun() {
            if (racun == null) {
                racun = new ArrayList<BankeSema.KorisnickiRacuni.Racun>();
            }
            return this.racun;
        }


        
        public BankeSema.KorisnickiRacuni.Racun getRacunByNazivKlijenta(String naziv) {
        	for(BankeSema.KorisnickiRacuni.Racun r : getRacun()) {
        		if(r.getVlasnik().equals(naziv))
        			return r;
        	}
        	return null;
        }
        
        
        
        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="brojRacuna">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;length value="18"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="vlasnik">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="255"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="pib">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="11"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="stanje">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *               &lt;totalDigits value="15"/>
         *               &lt;fractionDigits value="2"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="blokiran" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="rezervisano">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *               &lt;totalDigits value="15"/>
         *               &lt;fractionDigits value="2"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "brojRacuna",
            "vlasnik",
            "pib",
            "stanje",
            "blokiran",
            "rezervisano"
        })
        public static class Racun {

            @XmlElement(required = true)
            protected String brojRacuna;
            @XmlElement(required = true)
            protected String vlasnik;
            @XmlElement(required = true)
            protected String pib;
            @XmlElement(required = true)
            protected BigDecimal stanje;
            protected boolean blokiran;
            @XmlElement(required = true)
            protected BigDecimal rezervisano;

            /**
             * Gets the value of the brojRacuna property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBrojRacuna() {
                return brojRacuna;
            }

            /**
             * Sets the value of the brojRacuna property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBrojRacuna(String value) {
                this.brojRacuna = value;
            }

            /**
             * Gets the value of the vlasnik property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVlasnik() {
                return vlasnik;
            }

            /**
             * Sets the value of the vlasnik property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVlasnik(String value) {
                this.vlasnik = value;
            }

            /**
             * Gets the value of the pib property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPib() {
                return pib;
            }

            /**
             * Sets the value of the pib property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPib(String value) {
                this.pib = value;
            }

            /**
             * Gets the value of the stanje property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getStanje() {
                return stanje;
            }

            /**
             * Sets the value of the stanje property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setStanje(BigDecimal value) {
                this.stanje = value;
            }

            /**
             * Gets the value of the blokiran property.
             * 
             */
            public boolean isBlokiran() {
                return blokiran;
            }

            /**
             * Sets the value of the blokiran property.
             * 
             */
            public void setBlokiran(boolean value) {
                this.blokiran = value;
            }

            /**
             * Gets the value of the rezervisano property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getRezervisano() {
                return rezervisano;
            }

            /**
             * Sets the value of the rezervisano property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setRezervisano(BigDecimal value) {
                this.rezervisano = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="nerealizovanNalog">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="vrstaNaloga" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element ref="{http://www.toomanysecrets.com/nalog}nalog"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nerealizovanNalog"
    })
    public static class NerealizovaniNalozi {

        protected List<BankeSema.NerealizovaniNalozi.NerealizovanNalog> nerealizovanNalog;

        /**
         * Gets the value of the nerealizovanNalog property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nerealizovanNalog property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNerealizovanNalog().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BankeSema.NerealizovaniNalozi.NerealizovanNalog }
         * 
         * 
         */
        public List<BankeSema.NerealizovaniNalozi.NerealizovanNalog> getNerealizovanNalog() {
            if (nerealizovanNalog == null) {
                nerealizovanNalog = new ArrayList<BankeSema.NerealizovaniNalozi.NerealizovanNalog>();
            }
            return this.nerealizovanNalog;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="vrstaNaloga" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element ref="{http://www.toomanysecrets.com/nalog}nalog"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "vrstaNaloga",
            "nalog"
        })
        public static class NerealizovanNalog {

            @XmlElement(required = true)
            protected String vrstaNaloga;
            @XmlElement(namespace = "http://www.toomanysecrets.com/nalog", required = true)
            protected Nalog nalog;

            /**
             * Gets the value of the vrstaNaloga property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVrstaNaloga() {
                return vrstaNaloga;
            }

            /**
             * Sets the value of the vrstaNaloga property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVrstaNaloga(String value) {
                this.vrstaNaloga = value;
            }

            /**
             * Gets the value of the nalog property.
             * 
             * @return
             *     possible object is
             *     {@link Nalog }
             *     
             */
            public Nalog getNalog() {
                return nalog;
            }

            /**
             * Sets the value of the nalog property.
             * 
             * @param value
             *     allowed object is
             *     {@link Nalog }
             *     
             */
            public void setNalog(Nalog value) {
                this.nalog = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="realizovanNalog">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.toomanysecrets.com/nalog}nalog"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "realizovanNalog"
    })
    public static class RealizovaniNalozi {

        protected List<BankeSema.RealizovaniNalozi.RealizovanNalog> realizovanNalog;

        /**
         * Gets the value of the realizovanNalog property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the realizovanNalog property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRealizovanNalog().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BankeSema.RealizovaniNalozi.RealizovanNalog }
         * 
         * 
         */
        public List<BankeSema.RealizovaniNalozi.RealizovanNalog> getRealizovanNalog() {
            if (realizovanNalog == null) {
                realizovanNalog = new ArrayList<BankeSema.RealizovaniNalozi.RealizovanNalog>();
            }
            return this.realizovanNalog;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.toomanysecrets.com/nalog}nalog"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nalog"
        })
        public static class RealizovanNalog {

            @XmlElement(namespace = "http://www.toomanysecrets.com/nalog", required = true)
            protected Nalog nalog;

            /**
             * Gets the value of the nalog property.
             * 
             * @return
             *     possible object is
             *     {@link Nalog }
             *     
             */
            public Nalog getNalog() {
                return nalog;
            }

            /**
             * Sets the value of the nalog property.
             * 
             * @param value
             *     allowed object is
             *     {@link Nalog }
             *     
             */
            public void setNalog(Nalog value) {
                this.nalog = value;
            }

        }

    }

}
