//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.23 at 11:07:43 PM CEST 
//


package basexdb.banka;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.toomanysecrets.bankesema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.toomanysecrets.bankesema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BankeSema }
     * 
     */
    public BankeSema createBankeSema() {
        return new BankeSema();
    }

    /**
     * Create an instance of {@link BankeSema.BrojacPoslednjegPrimljenogZahtevaZaIzvod }
     * 
     */
    public BankeSema.BrojacPoslednjegPrimljenogZahtevaZaIzvod createBankeSemaBrojacPoslednjegPrimljenogZahtevaZaIzvod() {
        return new BankeSema.BrojacPoslednjegPrimljenogZahtevaZaIzvod();
    }

    /**
     * Create an instance of {@link BankeSema.BrojacPoslednjegPrimljenogNaloga }
     * 
     */
    public BankeSema.BrojacPoslednjegPrimljenogNaloga createBankeSemaBrojacPoslednjegPrimljenogNaloga() {
        return new BankeSema.BrojacPoslednjegPrimljenogNaloga();
    }

    /**
     * Create an instance of {@link BankeSema.BrojacPoslednjePrimljeneNotifikacije }
     * 
     */
    public BankeSema.BrojacPoslednjePrimljeneNotifikacije createBankeSemaBrojacPoslednjePrimljeneNotifikacije() {
        return new BankeSema.BrojacPoslednjePrimljeneNotifikacije();
    }

    /**
     * Create an instance of {@link BankeSema.NerealizovaniNalozi }
     * 
     */
    public BankeSema.NerealizovaniNalozi createBankeSemaNerealizovaniNalozi() {
        return new BankeSema.NerealizovaniNalozi();
    }

    /**
     * Create an instance of {@link BankeSema.RealizovaniNalozi }
     * 
     */
    public BankeSema.RealizovaniNalozi createBankeSemaRealizovaniNalozi() {
        return new BankeSema.RealizovaniNalozi();
    }

    /**
     * Create an instance of {@link BankeSema.KorisnickiRacuni }
     * 
     */
    public BankeSema.KorisnickiRacuni createBankeSemaKorisnickiRacuni() {
        return new BankeSema.KorisnickiRacuni();
    }

    /**
     * Create an instance of {@link BankeSema.BrojacPoslednjegPrimljenogZahtevaZaIzvod.Firma }
     * 
     */
    public BankeSema.BrojacPoslednjegPrimljenogZahtevaZaIzvod.Firma createBankeSemaBrojacPoslednjegPrimljenogZahtevaZaIzvodFirma() {
        return new BankeSema.BrojacPoslednjegPrimljenogZahtevaZaIzvod.Firma();
    }

    /**
     * Create an instance of {@link BankeSema.BrojacPoslednjegPrimljenogNaloga.Firma }
     * 
     */
    public BankeSema.BrojacPoslednjegPrimljenogNaloga.Firma createBankeSemaBrojacPoslednjegPrimljenogNalogaFirma() {
        return new BankeSema.BrojacPoslednjegPrimljenogNaloga.Firma();
    }

    /**
     * Create an instance of {@link BankeSema.BrojacPoslednjePrimljeneNotifikacije.Centralnabanka }
     * 
     */
    public BankeSema.BrojacPoslednjePrimljeneNotifikacije.Centralnabanka createBankeSemaBrojacPoslednjePrimljeneNotifikacijeCentralnabanka() {
        return new BankeSema.BrojacPoslednjePrimljeneNotifikacije.Centralnabanka();
    }

    /**
     * Create an instance of {@link BankeSema.NerealizovaniNalozi.NerealizovanNalog }
     * 
     */
    public BankeSema.NerealizovaniNalozi.NerealizovanNalog createBankeSemaNerealizovaniNaloziNerealizovanNalog() {
        return new BankeSema.NerealizovaniNalozi.NerealizovanNalog();
    }

    /**
     * Create an instance of {@link BankeSema.RealizovaniNalozi.RealizovanNalog }
     * 
     */
    public BankeSema.RealizovaniNalozi.RealizovanNalog createBankeSemaRealizovaniNaloziRealizovanNalog() {
        return new BankeSema.RealizovaniNalozi.RealizovanNalog();
    }

    /**
     * Create an instance of {@link BankeSema.KorisnickiRacuni.Racun }
     * 
     */
    public BankeSema.KorisnickiRacuni.Racun createBankeSemaKorisnickiRacuniRacun() {
        return new BankeSema.KorisnickiRacuni.Racun();
    }

}
