//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.18 at 12:56:47 AM CEST 
//


package crlCentralna;

import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bank" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="date">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *                         &lt;minInclusive value="1900-01-01"/>
 *                         &lt;maxInclusive value="2200-01-01"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="certificateID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bank"
})
@XmlRootElement(name = "crlCentralna")
public class CrlCentralna {

    protected List<CrlCentralna.Bank> bank;

    /**
     * Gets the value of the bank property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bank property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBank().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CrlCentralna.Bank }
     * 
     * 
     */
    public List<CrlCentralna.Bank> getBank() {
        if (bank == null) {
            bank = new ArrayList<CrlCentralna.Bank>();
        }
        return this.bank;
    }
    
    public void setBank(List<CrlCentralna.Bank> banks) {
    	this.bank = banks;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="date">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
     *               &lt;minInclusive value="1900-01-01"/>
     *               &lt;maxInclusive value="2200-01-01"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="certificateID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "date",
        "certificateID"
    })
    public static class Bank {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true, type = String.class)
        @XmlJavaTypeAdapter(Adapter1 .class)
        protected Date date;
        @XmlElement(required = true)
        protected List<String> certificateID = new ArrayList<>();

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Date getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDate(Date value) {
            this.date = value;
        }

        /**
         * Gets the value of the certificateID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the certificateID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCertificateID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCertificateID() {
            if (certificateID == null) {
                certificateID = new ArrayList<String>();
            }
            return this.certificateID;
        }
        
        public void addCertificateID(String id) {
        	if(!this.certificateID.contains(id))
        		this.certificateID.add(id);
        }

    }
    
    public Bank getBankByName(String name){
		Bank ret = null;
		for(Bank b: getBank()){
			if(b.getName().equals(name))
				ret = b;				
		}
		return ret;
	}

	public Bank removeBank(String name){
		Bank ret = getBankByName(name);
		if(ret != null) {
			bank.remove(ret);
			return ret;
		}
		return null;
	}
	
	public void addBank(Bank bankTemp){
		Bank temp = null;
		for(Bank b: getBank()){
			if(b.getName().equals(bankTemp.getName())){
				temp = b;
			}				
		}
		if(temp == null) {
			getBank().add(bankTemp);
		} else {
			removeBank(temp.getName());
			temp.addCertificateID(bankTemp.getCertificateID().get(0));
			getBank().add(temp);
		}
	}
    
	public static CrlCentralna load(String name) {
		
		//XML -> Objektni model
		
		try {
			//Definisemo kontekst, tj. paket(e) u kome se nalaze bean-ovi
			JAXBContext context1 = JAXBContext.newInstance("crlCentralna");
			//Klasa za XML -> objektni model
			Unmarshaller unmarshaller = context1.createUnmarshaller();
			//Transformacija u objektni model
			CrlCentralna crlCentralna = (CrlCentralna) unmarshaller.unmarshal(new File(name));
			//ispis na ekran
			System.out.println(crlCentralna);
			return crlCentralna;
			
		} catch (JAXBException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return null;
		}
		//Sad moze da se menja objeknti model
	}

}
