//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.19 at 12:29:31 AM CEST 
//


package firms;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.PropertyException;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import util.NSPrefixMapper;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.toomanysecrets.com/firme}firm" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "firm"
})
@XmlRootElement(name = "registeredFirms")
public class RegisteredFirms {

    @XmlElement(required = true)
    protected List<Firm> firm;

    /**
     * Gets the value of the firm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the firm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFirm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Firm }
     * 
     * 
     */
    public List<Firm> getFirm() {
        if (firm == null) {
            firm = new ArrayList<Firm>();
        }
        return this.firm;
    }
    
    public void setFirm(List<Firm> firm) {
		this.firm = firm;
	}



	public void addFirm(Firm f) {
		this.firm.add(f);
	}

	public Firm getFirmByPib(String pib){
		Firm ret = null;
		for(Firm f: firm){
			if(f.getPib().equals(pib))
				ret = f;				
		}
		return ret;
	}

	public Firm getFirmByAcc(String acc){
		Firm ret = null;
		for(Firm f:firm){
			if(f.getAccount().equals(acc))
				ret = f;				
		}
		return ret;
	}

	public Firm removeFirm(String pib){
		Firm ret = getFirmByPib(pib);
		if(ret != null) {
			firm.remove(ret);
			return ret;
		}
		return null;
	}
	
	public static RegisteredFirms load(String name) {
		
		//XML -> Objektni model
		
		try {
			//Definisemo kontekst, tj. paket(e) u kome se nalaze bean-ovi
			JAXBContext context1 = JAXBContext.newInstance("firms");
			//Klasa za XML -> objektni model
			Unmarshaller unmarshaller = context1.createUnmarshaller();
			//Transformacija u objektni model
			RegisteredFirms registeredFirms = (RegisteredFirms) unmarshaller.unmarshal(new File("./xsdSchemas/"+name+".xml"));
			//ispis na ekran
			System.out.println(registeredFirms);
			return registeredFirms;
			
		} catch (JAXBException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return null;
		}
		//Sad moze da se menja objeknti model
	}
	
	public void store(List<Firm> firms, String name) {
		
		//Objeknti model -> XML
		
		//Definisemo kontekst, tj. paket(e) u kome se nalaze bean-ovi
		//Posto je isti kontekst moze se koristiti i klasa context1
		try {
			JAXBContext context2 = JAXBContext.newInstance("firms");
			//Klasa za transformisanje objektnog modela u XML
			Marshaller marshaller = context2.createMarshaller();
			//na ovaj naci se setuje koji prefiks se koristi za koji namespace
			marshaller.setProperty("com.sun.xml.bind.namespacePrefixMapper", new NSPrefixMapper());
			//da se radi identacija
			marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
			//serijaliacija na System.out stream
			RegisteredFirms registeredFirms = new RegisteredFirms();
			registeredFirms.setFirm(firms);
			marshaller.marshal(registeredFirms, new BufferedWriter(new FileWriter(new File("./xsdSchemas/"+name+".xml"))));
		} catch (PropertyException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (JAXBException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
